name: test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get dependencies
        run: go get -t -d ./...
      - name: Test
        run: go test ./...